services:
  mongo:
    image: mongo:5.0.3
    restart: always
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:6.2.6-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    depends_on:
      - mongodb
      - redis
    restart: on-failure
    env_file: .env.prod
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - api
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:worker
    depends_on:
      - api
    restart: on-failure
    env_file: .env.prod
  bot:
    build:
      context: ../bot
      dockerfile: Dockerfile
    depends_on:
      - worker
    restart: on-failure
    env_file: .env.prod
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
