services:
  mongo:
    image: mongo:5.0.3
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis:6.2.6-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local